-- research.stakeholders_to_gdp definition
-- Drop table
-- DROP TABLE research.stakeholders_to_gdp;
CREATE TABLE research.stakeholders_to_gdp (
    stakeholder_gdp_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    stakeholder_id int4 NULL,
    gdp numeric NOT NULL,
    gdp_year int4 NOT NULL,
    CONSTRAINT stakeholders_to_gdp_stakeholder_id_fkey FOREIGN KEY (stakeholder_id) REFERENCES public.stakeholders(id)
);